// Mocks generated by Mockito 5.3.2 from annotations
// in news_app/test/data/repository/config_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dio/dio.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:news_app/data/models/base_response.dart' as _i2;
import 'package:news_app/data/models/configuration.dart' as _i5;
import 'package:news_app/data/remote/config/config_api.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBaseResponse_0<T> extends _i1.SmartFake
    implements _i2.BaseResponse<T> {
  _FakeBaseResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ConfigApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfigApi extends _i1.Mock implements _i3.ConfigApi {
  MockConfigApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.BaseResponse<List<_i5.Configuration>>> getListConfig() =>
      (super.noSuchMethod(
        Invocation.method(
          #getListConfig,
          [],
        ),
        returnValue:
            _i4.Future<_i2.BaseResponse<List<_i5.Configuration>>>.value(
                _FakeBaseResponse_0<List<_i5.Configuration>>(
          this,
          Invocation.method(
            #getListConfig,
            [],
          ),
        )),
      ) as _i4.Future<_i2.BaseResponse<List<_i5.Configuration>>>);
  @override
  _i4.Future<T> processRequest<T>(
    _i4.Future<_i6.Response<dynamic>> Function()? request,
    T Function(dynamic)? build,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #processRequest,
          [
            request,
            build,
          ],
        ),
        returnValue: _i4.Future<T>.value(null),
      ) as _i4.Future<T>);
}
